version: "3.6"
networks:
  node1-net:
  node2-net:
# Uncomment next line if you want to bring Charlie's node up
#  node3-net:
  directory-net:
  nodes:
  backend-directory-net:
services:
# ----------------------------------------- Logion node 1 --------------------------------------------------------------
  private-database1:
    image: logionnetwork/logion-postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
      - ENC_PASSWORD=secret
    networks:
      - node1-net
    volumes:
      - ./db_backup:/db_backup
  node1:
    image: logionnetwork/logion-node:${NODE_TAG:-latest}
    environment:
      - NODE_KEY=c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a
      - CUSTOM_OPTIONS=--alice --no-mdns --ws-external --rpc-cors all
      - CHAIN_SPEC=test
    networks:
      - node1-net
      - nodes
  backend1:
    image: logionnetwork/logion-backend:${BACKEND_TAG:-latest}
    environment:
      - JWT_SECRET=c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a
      - JWT_ISSUER=12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2
      - TYPEORM_HOST=private-database1
      - WS_PROVIDER_URL=ws://node1:9944
      - OWNER=5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - DIRECTORY_URL=http://directory:8080
      - SMTP_ENABLED=false
    depends_on:
      - node1
      - private-database1
    networks:
      - node1-net
      - backend-directory-net
  frontend1:
    image: logionnetwork/logion-frontend:${FRONTEND_TAG:-latest}
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:9944:9944
    volumes:
    - ./front_config.js:/usr/share/nginx/html/config.js
    - ./front_web1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - node1
    environment:
      - CERTBOT_EMAIL=user1@invalid.domain
      - BACKEND_HOST_PORT=backend1:8080
      - NODE_HOST_PORT=node1:9944
    networks:
      - node1-net
  ipfs1:
    image: ipfs/go-ipfs:v0.12.0
    ports:
      - 127.0.0.1:5001:5001
    volumes:
      - ./config/ipfs1/config:/data/ipfs/config:ro
      - ./config/ipfs1/datastore_spec:/data/ipfs/datastore_spec:ro
      - ./config/ipfs1/swarm.key:/data/ipfs/swarm.key:ro
      - ./config/ipfs1/version:/data/ipfs/version:ro
    networks:
      - nodes
  ipfs-cluster1:
    image: ipfs/ipfs-cluster:v0.14.5
    depends_on:
      - ipfs1
    ports:
      - 127.0.0.1:9094:9094
    volumes:
      - ./config/ipfs-cluster1/identity.json:/data/ipfs-cluster/identity.json:ro
      - ./config/ipfs-cluster1/service.json:/data/ipfs-cluster/service.json:ro
    networks:
      - nodes
# ----------------------------------------- Logion node 2 --------------------------------------------------------------
  private-database2:
    image: logionnetwork/logion-postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
    networks:
      - node2-net
  node2:
    image: logionnetwork/logion-node:${NODE_TAG:-latest}
    environment:
      - NODE_KEY=6ce3be907dbcabf20a9a5a60a712b4256a54196000a8ed4050d352bc113f8c58
      - CUSTOM_OPTIONS=--bob --no-mdns --bootnodes /dns4/node1/tcp/30333/p2p/12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2 --ws-external --rpc-cors all
      - CHAIN_SPEC=test
    depends_on:
      - node1
    networks:
      - node2-net
      - nodes
  backend2:
    image: logionnetwork/logion-backend:${BACKEND_TAG:-latest}
    environment:
      - JWT_SECRET=6ce3be907dbcabf20a9a5a60a712b4256a54196000a8ed4050d352bc113f8c58
      - JWT_ISSUER=12D3KooWQYV9dGMFoRzNStwpXztXaBUjtPqi6aU76ZgUriHhKust
      - TYPEORM_HOST=private-database2
      - WS_PROVIDER_URL=ws://node2:9944
      - OWNER=5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
      - DIRECTORY_URL=http://directory:8080
      - SMTP_ENABLED=false
    depends_on:
      - node2
      - private-database2
    networks:
      - node2-net
      - backend-directory-net
  frontend2:
    image: logionnetwork/logion-frontend:${FRONTEND_TAG:-latest}
    ports:
      - 127.0.0.1:8081:80
      - 127.0.0.1:9945:9944
    volumes:
    - ./front_config.js:/usr/share/nginx/html/config.js
    - ./front_web2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend2
      - node2
    environment:
      - CERTBOT_EMAIL=user2@invalid.domain
      - BACKEND_HOST_PORT=backend2:8080
      - NODE_HOST_PORT=node2:9944
    networks:
      - node2-net
  ipfs2:
    image: ipfs/go-ipfs:v0.12.0
    volumes:
      - ./config/ipfs2/config:/data/ipfs/config:ro
      - ./config/ipfs2/datastore_spec:/data/ipfs/datastore_spec:ro
      - ./config/ipfs2/swarm.key:/data/ipfs/swarm.key:ro
      - ./config/ipfs2/version:/data/ipfs/version:ro
    networks:
      - nodes
    depends_on:
      - ipfs1
  ipfs-cluster2:
    image: ipfs/ipfs-cluster:v0.14.5
    depends_on:
      - ipfs-cluster1
      - ipfs2
    volumes:
      - ./config/ipfs-cluster2/identity.json:/data/ipfs-cluster/identity.json:ro
      - ./config/ipfs-cluster2/service.json:/data/ipfs-cluster/service.json:ro
    networks:
      - nodes
# ----------------------------------------- Logion node 3 --------------------------------------------------------------
# Uncomment below section if you want to bring Charlie's node up
  # private-database3:
  #   image: logionnetwork/logion-postgres:latest
  #   environment:
  #     - POSTGRES_PASSWORD=secret
  #   networks:
  #     - node3-net
  # node3:
  #   image: logionnetwork/logion-node:${NODE_TAG:-latest}
  #   environment:
  #     - NODE_KEY=3a9d5b35b9fb4c42aafadeca046f6bf56107bd2579687f069b42646684b94d9e
  #     - CUSTOM_OPTIONS=--charlie --no-mdns --bootnodes /dns4/node1/tcp/30333/p2p/12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2 --ws-external --rpc-cors all
  #     - CHAIN_SPEC=test
  #   networks:
  #     - node3-net
  #     - nodes
  # backend3:
  #   image: logionnetwork/logion-backend:${BACKEND_TAG:-latest}
  #   environment:
  #     - TYPEORM_HOST=private-database3
  #     - WS_PROVIDER_URL=ws://node3:9944
  #     - OWNER=5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y
  #     - DIRECTORY_URL=http://directory:8080
  #     - SMTP_ENABLED=false
  #   depends_on:
  #     - node3
  #     - private-database3
  #   networks:
  #     - node3-net
  #     - backend-directory-net
  # frontend3:
  #   image: logionnetwork/logion-frontend:${FRONTEND_TAG:-latest}
  #   ports:
  #     - 127.0.0.1:8082:80
  #     - 127.0.0.1:9946:9944
  #   volumes:
  #   - ./front_config.js:/usr/share/nginx/html/config.js
  #   - ./front_web3.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend3
  #     - node3
  #   environment:
  #     - CERTBOT_EMAIL=user3@invalid.domain
  #     - BACKEND_HOST_PORT=backend3:8080
  #     - NODE_HOST_PORT=node3:9944
  #   networks:
  #     - node3-net
# ----------------------------------------- Logion directory --------------------------------------------------------------
  directory-database:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=secret
    networks:
      - directory-net
  directory:
    image: logionnetwork/logion-directory:${BACKEND_TAG:-latest}
    ports:
      - 127.0.0.1:8090:8080
    environment:
      - JWT_SECRET=c12b6d18942f5ee8528c8e2baf4e147b5c5c18710926ea492d09cbd9f6c9f82a
      - JWT_ISSUER=12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2
      - WS_PROVIDER_URL=ws://node1:9944
      - TYPEORM_HOST=directory-database
    depends_on:
      - node1
      - directory-database
    networks:
      - nodes
      - directory-net
      - backend-directory-net
