version: "3.6"
services:
  private-database:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
  node:
    image: logionnetwork/logion-node:${NODE_TAG:-latest}
    ports:
      - 9944:9944
  backend:
    image: logionnetwork/logion-backend:${BACKEND_TAG:-latest}
    environment:
      - TYPEORM_HOST=private-database
      - WS_PROVIDER_URL=ws://node:9944
    depends_on:
      - node
      - private-database
  frontend:
    image: logionnetwork/logion-frontend:${FRONTEND_TAG:-latest}
    ports:
      - 80:80
    volumes:
    - ./front_config.js:/usr/share/nginx/html/config.js
    - ./front_web.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    environment:
      - CERTBOT_EMAIL=user@invalid.domain
      - STAGING=1
      - BACKEND_HOST_PORT=backend:8080
      - NODE_HOST_PORT=node:9944
